### ISSUE TITLE
Rasterific-0.5 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [Twinside/Rasterific#19]
Citing from http://hydra.cryp.to/build/536970/nixlog/3/raw:

    Preprocessing test suite 'test' for Rasterific-0.5...

    exec-src/rastertest.hs:26:8:
        Could not find module ‘Arbitrary’
        Use -v to see a list of the files searched for.

    exec-src/rastertest.hs:34:18:
        Could not find module ‘Sample’
        Use -v to see a list of the files searched for.

**Comment by Twinside** [comment]
Thanks
