### ISSUE TITLE
Rasterific-0.5.0.1 test suite failure

### ISSUE THREAD

**Issue by peti** [Twinside/Rasterific#20]
Citing from http://hydra.cryp.to/build/537553/nixlog/2/raw:

    running tests
    Running 1 test suites...
    Test suite test: RUNNING...
    test: user error (Pattern match failure in do expression at exec-src/rastertest.hs:612:3-26)
    Test suite test: FAIL

**Comment by Twinside** [comment]
Completly removed the test suite in the latest hackage version, it was depending on files present in the repository, which doesn't really have it's place in the distribution.
