### ISSUE TITLE
Can't render a drawing with PixelRGB8

### ISSUE THREAD

**Issue by leohaskell** [Twinside/Rasterific#25]
In the documentations is written:
```haskell
type RenderablePixel px = ...
```
```
...
All pixel instances of JuicyPixels should be usable.
...
Tested pixels type are PixelRGBA8 and Pixel8, pixel types in other colorspace will probably produce weird results.
...
```

But with PixelRGB8 it doesn't even compile:
```
No instance for (Num (Codec.Picture.Types.PackedRepresentation PixelRGB8))
arising from a use of ‘renderDrawing’
```

Is there a way to do this?
If not, please change the documentation, so that it's clear which Pixel types can be used.

**Comment by Twinside** [comment]
Looks like outdated documentation to me, it probably was true at the beginning.
