### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by SwiftsNamesake** [Twinside/Rasterific#30]
I'm in the process of fixing the typos in the Haddocks, and came across this:

https://github.com/Twinside/Rasterific/blob/6aa707130308f9c41a6578079809ce88c4e51480/src/Graphics/Rasterific.hs#L130

I just wonder what you mean by 'traduction' (translation, maybe, as in translating coordinates), and also why there are three asterisks (***) rather than one.

**Comment by SwiftsNamesake** [comment]
Also:

```
-- | Will stroke geometry with a given stroke width.
-- The elements should be connected
```

It should be **Fill* instead of **Will** right?

**Comment by Twinside** [comment]
Answered in pull request
