### ISSUE TITLE
Integration with a GUI library

### ISSUE THREAD

**Issue by samvv** [Twinside/Rasterific#35]
Hi, thanks for the great library! I'm trying it out now.

Sorry for the noob question, but is it possible to integrate the drawn image directly into some other GUI framework, say [WX](https://wiki.haskell.org/WxHaskell) without going through the file system? I'd like to use this library as the drawing engine for a small game I'm writing. 

Thanks!

**Comment by Twinside** [comment]
I guess it should be possible by passing through the `imageData` of the generated `Image`, which is a `Storable` vector, and can be used as raw pointer (potentially usable by C callbacks). See [Storable vector](https://hackage.haskell.org/package/vector-0.12.0.1/docs/Data-Vector-Storable.html#g:36) documentation on raw pointer for more hints. Hopefully wx provides primitives to import it, at worst, you may have to copy the Vector as an Array and use `imageCreateFromPixelArray` (I'm not that knoweledgeable about wx), it would still a magnitude faster than storing then loading a file again.

**Comment by samvv** [comment]
Thanks for the info! Will try it out when I'm done with another project.
