### ISSUE TITLE
Not full black pixel on crossing

### ISSUE THREAD

**Issue by Twinside** [Twinside/Rasterific#36]
see diagrams/diagrams-rasterific#42 for more details

**Comment by Twinside** [comment]
Ok I've investigated, and the behavior is normal in this engine. This is part of the anti-aliasing,
and anti-aliased edges are alpha blended hence the halving behavior you have seen, we don't
accumulate sub-pixel coverage anywhere, but in internal structure while drawing.

So what it means, to get read of a non-full black pixel, you have (or manage to get Diagrams)
draw the bunch of lines in  a whole call, to reuse your unit test:

``` haskell
strokePixelTest :: (forall g. Stroker g) -> IO ()
strokePixelTest stroker =
    produceImageAtSize 10 5 "stroke_pixel.png"
        $ withTexture (uniformTexture black)
        $ drawing
  where
    drawing = sequence_ $
          [ stroker 1 JoinRound (CapStraight 0, CapStraight 0) (lineFromPath p)
          | p <- ps ]
    ps = -- line of 1, 2, 3 pixels
         [ [ V2 1 1.5, V2 2 1.5 ]
         , [ V2 3 1.5, V2 5 1.5 ]
         , [ V2 6 1.5, V2 9 1.5 ]
         -- line of halved lines
         --  [ V2 1 3.5, V2 1.5 3.5 ]
         -- , [ V2 1.5 3.5, V2 2 3.5 ]
         , [ V2 1 3.5, V2 1.5 3.5, V2 2 3.5  ]

         -- , [ V2 3 3.5, V2 4 3.5 ]
         -- , [ V2 4 3.5, V2 5 3.5 ]
         , [ V2 3 3.5, V2 4 3.5, V2 5 3.5  ]

         -- , [ V2 6 3.5, V2 7.5 3.5 ]
         -- , [ V2 7.5 3.5, V2 9 3.5 ]
         , [ V2 6 3.5, V2 7.5 3.5, V2 9 3.5 ]
         ]
```

By stroking both lines beginning at half points in the same call, the engine will
perform correct sub-pixel accumulation and provide correct result.

As a small test, I've tried to reproduce a similar test with the HTML5 Canvas API, to see the result:

``` html
<!DOCTYPE html>
<html>
    <head><title>canvas</title></head>
    <body><canvas id="canvas" width="30" height="30"></canvas></body>
    <script>
        var canvas = document.getElementById('canvas');
        var ctx = canvas.getContext('2d');

        const xOffset = 0.5;
        ctx.fillStyle = 'black';
        ctx.beginPath();
        ctx.lineWidth = 1;
        ctx.moveTo(1 + xOffset, 3);
        ctx.lineTo(1.5 + xOffset, 3);
        ctx.stroke();

        ctx.beginPath();
        ctx.lineWidth = 1;
        ctx.moveTo(1.5 + xOffset, 3);
        ctx.lineTo(2 + xOffset, 3);
        ctx.stroke();

        const offset = 0.5;
        ctx.beginPath();
        ctx.moveTo(1 + xOffset, 10 + offset);
        ctx.lineWidth = 1;
        ctx.lineTo(1.5 + xOffset, 10 + offset);
        ctx.moveTo(1.5 + xOffset, 10 + offset);
        ctx.lineTo(2 + xOffset, 10 + offset);
        ctx.stroke();
    </script>
</html>
```

So with Firefox (I think it's Cairo for backend) and Chrome (Skia) all I could get was:
![browser_render](https://user-images.githubusercontent.com/168874/37873151-9b0a1ca4-3016-11e8-8cd8-97a1caa27362.png)

So clearly not black :/

**Comment by robx** [comment]
Thanks for checking. Yes, I can reproduce this with firefox canvas.

On the other hand I get perfect black pixels with diagrams' cairo backend https://github.com/diagrams/diagrams-cairo. I don't immediately see diagrams-cairo doing anything fancy, so I'm really curious what's going on here...

**Comment by Twinside** [comment]
I think I get it

Looking at [diagrams-rasterific](https://github.com/diagrams/diagrams-rasterific/blob/master/src/Diagrams/Backend/Rasterific.hs#L332):

``` haskell
renderPath :: TypeableFloat n => Path V2 n -> [[R.Primitive]]
renderPath p = -- Implementation not important, the type is important

-- Stroke both dashed and solid lines.
mkStroke :: TypeableFloat n => n ->  R.Join -> (R.Cap, R.Cap) -> Maybe (R.DashPattern, n)
      -> [[R.Primitive]] -> RenderR ()
mkStroke (realToFrac -> l) j c d primList =
  maybe (mapM_ (R.stroke l j c) primList)
        (\(dsh, off) -> mapM_ (R.dashedStrokeWithOffset (realToFrac off) dsh l j c) primList)
```

What looks weird and completly fit the previous analysis is the mapM_ of mkStroke, we stroke every line separately instead of doing it "in group". Looking at [diagrams-cairo path rendering](https://github.com/diagrams/diagrams-cairo/blob/master/src/Diagrams/Backend/Cairo/Internal.hs#L316):

```haskell
instance Renderable (Path V2 Double) Cairo where
  render _ p = C $ do
    cairoPath p
    f <- getStyleAttrib getFillTexture
    s <- getStyleAttrib getLineTexture
    ign <- use ignoreFill
    setTexture f
    when (isJust f && not ign) $ liftC C.fillPreserve
    setTexture s
    liftC C.stroke
```

We call stroke only once for the whole path. I guess there is a need to patch diagrams-rasterific :]

**Comment by Twinside** [comment]
Pull request proposed to `diagrams-rasterific`, closing this ticket

**Comment by robx** [comment]
Great, thank you! (I can confirm this: If I split the offending path into separate paths, I get the same gray pixels with cairo.)
