### ISSUE TITLE
Hangs and eats all memory trying to render a complex diagram.

### ISSUE THREAD

**Issue by kindaro** [Twinside/Rasterific#53]
Unfortunately, I do not have a short example. I am trying stuff with graphs, and one thing I did was to render a graph in some fashion. I discovered that, while I could vectorize it with the SVG back end, if I try to do the same with Rasterific, it eats all memory in an infinite loop. I did some profiling and I found out that the looping function is `clipLine`.

Here is [the commit][1]. You can run it with, for example, `cabal run exes -- --output x.png --width 200`. It hangs when I try it. If you replace `clr489` example graph with, say, `cyc3`, it will render beautifully.

[1]: https://github.com/kindaro/draw-graph/tree/cb5d3e496cc53924ee9ac133e0010614b992a0b7

Here is the [profiling log][2].

[2]: https://gist.github.com/kindaro/1f2f2c1d58c88f5367a33f054685936d

Please let me know if it hangs on your machine too, and if I can do anything else to help.

**Comment by Twinside** [comment]
Can you try to call [dumpDrawing](http://hackage.haskell.org/package/Rasterific-0.7.4.4/docs/Graphics-Rasterific.html#v:dumpDrawing) somehow a put the result somewhere?

Dump drawing should print-out the scene in nearly haskell, workable for debugging

**Comment by kindaro** [comment]
1. I have no idea how to get that for you. I asked: diagrams/diagrams-rasterific#60.
2. I found a ticket diagrams/diagrams-rasterific#39 that may be relevant.

**Comment by Twinside** [comment]
You have infinitys and NaNs and the dumped diagram:

```
(fill [LinePrim Line (V2 (-Infinity) (-Infinity)) (V2 (-Infinity) (-Infinity)),LinePrim Line (V2 (-Infinity) (-Infinity)) (V2 (-Infinity) (-Infinity)),LinePrim Line (V2 (-Infinity) (-Infinity)) (V2 (-Infinity) (-Infinity)),LinePrim Line (V2 (-Infinity) (-Infinity)) (V2 NaN NaN)] >>=
```

This is not filtered by Rasterific, and yeah, it makes the rendering go bonker.

**Comment by kindaro** [comment]
@Twinside Thank you for taking time to research this issue.

So what can be done?

I am not sure I can control this. The data I supply to the `diagrams` API is somewhat shady _(like, `sin pi` shady)_, but it is legit. The same diagrams render flawlessly with SVG back end.

Can you explain to me what data type you are showing, and maybe post the code you used to obtain it, so that I can examine my various diagrams with it and locate what goes wrong?

**Comment by Twinside** [comment]
I've tried the SVG, and you have NaN and Infinity written in your SVG (that your browser probably ignore, I wouldn't call that flawless. The code is mostly the copy/past of Diagram.Rasterific with a call changed to dump the generated drawing, I've pushed it [here](https://github.com/Twinside/draw-graph).

I've added safegard to Rasterific for these cases, but the root problem remain
