### ISSUE TITLE
Oblivious Strokes

### ISSUE THREAD

**Issue by ibrahimsag** [Twinside/Rasterific#56]
Transformations and stroke commands don't seem to play well together.

This is not a major issue and i did not have time to find the root cause but i just wanted to see if it means something.

In this particular case, I placed the origin at the center of the image with a translation, but the stroke commands still took the top-left corner as the origin.

Great library! Gratitude!

**Comment by lancelet** [comment]
I have a test case for the bug above. AFAICT, transformations are being ignored completely for strokes.

Here is the test case:
```haskell
testCase :: IO ()
testCase = do
    let white     = PixelRGBA8 255 255 255 255
        strokeTex = withTexture (uniformTexture (PixelRGBA8 0 0x86 0xc1 255))
        fillTex   = withTexture (uniformTexture (PixelRGBA8 0 0x86 0xc1 80))
        geom      = circle (V2 0 0) 90
        stroked   = strokeTex $ stroke 5.0 JoinRound (CapRound, CapRound) geom
        filled    = fillTex $ fill geom
        xform     = translate (V2 100 100)
    let img = renderDrawing 200 200 white $ do
            withTransformation xform filled
            withTransformation xform stroked
    writePng "test-case.png" img
```

It results in the following output:
![test-case](https://user-images.githubusercontent.com/356739/78016019-f66ecf80-7395-11ea-9f9f-afe0b22a7ac0.png)

The expected result is that the stroked and filled shape should lie on top of each other. Instead, the stroked shape remains at the origin.

**Comment by lancelet** [comment]
A simple workaround for the bug is to manually stroke the path first, converting it into a fill-able geometry. For example, in the case described above:

```haskell
workaround :: IO ()
workaround = do
    let white     = PixelRGBA8 255 255 255 255
        strokeTex = withTexture (uniformTexture (PixelRGBA8 0 0x86 0xc1 255))
        fillTex   = withTexture (uniformTexture (PixelRGBA8 0 0x86 0xc1 80))
        geom      = circle (V2 0 0) 90
        strokized = strokize 5.0 JoinRound (CapRound, CapRound) geom
        stroked   = strokeTex $ fill strokized
        filled    = fillTex $ fill geom
        xform     = translate (V2 100 100)
    let img = renderDrawing 200 200 white $ do
            withTransformation xform filled
            withTransformation xform stroked
    writePng "workaround.png" img
```

Which indeed produces the expected output:
![workaround](https://user-images.githubusercontent.com/356739/78016934-3aae9f80-7397-11ea-8e80-1c4160697066.png)

**Comment by lancelet** [comment]
Addendum: for easier migration after the bug is fixed, I've defined:
```haskell
stroke'
  :: Geometry geom
  => Float
  -> Join
  -> (Cap, Cap)
  -> geom
  -> Drawing px ()
stroke' width join caps geometry = fill $ strokize width join caps geometry
```
Which seems to be behaving the way I expect `stroke` to behave (AFAICT - I don't know if there are any corner cases I haven't yet encountered).

**Comment by Twinside** [comment]
I've uploaded the fixed version to Hackage
